/**
 * generated by Xtext
 */
package org.osate.xtext.aadl2.instance.validation;

import org.osate.xtext.aadl2.instance.validation.AbstractInstanceValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class InstanceValidator extends AbstractInstanceValidator {
}
